name: gg_publish
description: Various tools and checks for publishing dart packages, e.g. versioning, checks etc.
version: 3.0.19
repository: https://github.com/inlavigo/gg_publish.git

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  args: ^2.4.2
  gg_args: ^2.0.1
  gg_console_colors: ^2.0.1
  gg_is_flutter: ^1.0.6
  gg_log: ^1.0.0
  gg_process: ^1.0.7
  gg_status_printer: ^1.0.7
  gg_version: ^4.0.2
  http: ^1.2.1
  matcher: ^0.12.16+1
  mocktail: ^1.0.3
  path: ^1.8.0
  pub_semver: ^2.1.4
  gg_git: ^3.0.0

dev_dependencies:
  fake_async: ^1.3.1
  gg_capture_print: ^1.0.3
  lints: ^6.0.0
  test: ^1.24.0