name: gg_publish
description: Various tools and checks for publishing dart packages, e.g. versioning, checks etc.
version: 1.1.2
repository: https://github.com/inlavigo/gg_publish.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  gg_args: ^1.0.8
  gg_console_colors: ^2.0.1
  gg_is_flutter: ^1.0.1
  gg_log: ^1.0.0
  gg_process: ^1.0.7
  gg_status_printer: ^1.0.7
  gg_version: ^1.0.5
  http: ^1.2.1
  mocktail: ^1.0.3
  path: ^1.8.0
  pub_semver: ^2.1.4

dev_dependencies:
  gg_capture_print: ^1.0.3
  gg_git: ^2.3.0
  gg_install_gg: ^1.0.1
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0
